export const TenantTableColumns: any[] = [
  {
    title: "",
    key: "expander",
    id: 1,
    width: "1%",
    isVisible: true,
  },
  {
    title: "Customer",
    dataIndex: "customer",
    key: "customer",
    id: 2,
    width: "25%",
    isVisible: true,
  },
  {
    title: "Domain",
    dataIndex: "domain",
    key: "domain",
    id: 3,
    width: "20%",
    isVisible: true,
  },
  {
    title: "Industry",
    dataIndex: "industry",
    key: "industry",
    id: 4,
    width: "20%",
    isVisible: true,
  },
  {
    title: "Plan",
    dataIndex: "plan",
    key: "plan",
    id: 5,
    width: "12%",
    isVisible: true,
  },
  {
    title: "Mode",
    dataIndex: "mode",
    key: "mode",
    id: 6,
    width: "12%",
    isVisible: true,
  },
  {
    title: "Is Active",
    dataIndex: "isActive",
    key: "isActive",
    id: 7,
    width: "20%",
    isVisible: true,
  },
];
