// export interface InvoiceDetails {
//   InvoiceLotDetailID: number;
//   InvoiceInvDetailID: number;
//   ItemMasterID: number;
//   SeqNo: number;
//   ItemID: number;
//   Barcode: string;
//   ItemName: string;
//   Description: string;
//   GroupName: string | null;
//   Quantity: number;
//   WSP: number;
//   MRP: number;
//   ListedMRP: number;
//   Rate: number;
//   Discount: number;
//   StdRate: number;
//   Amount: number;
//   OutputTax: number;
//   TaxAmount: number;
//   Charges: number;
//   EffRate: number;
//   TaxCode: number;
//   InputPer: number;
//   Oemcode: string;
//   Icode: string;
//   GRPCODE: number;
//   OrderQty: number;
//   PendingQty: number;
//   FOCQty: number;
//   OnlineMRP: number;
//   SplDiscount: number;
//   SetCode: string;
//   Cat1: string;
//   Cat2: string;
//   Cat3: string;
//   Cat4: string;
//   Cat5: string;
//   Cat6: string;
//   Cat7: string;
//   Cat8: string;
//   Cat9: string;
//   Cat10: string;
//   Cat11: string;
//   Cat12: string;
//   Cat13: string;
//   Cat14: string;
//   Cat15: string;
//   Cat16: string;
//   HSNCode: string | null;
//   ItemImage: string | null;
//   AgainstDetID: number;
//   AgainstInvoiceId: number;
//   AgainstInvoiceNo: string;
//   AgainstInvoiceDate: string;
//   ItemCode: string;
//   PSDetailId: number;
//   PSNo: string;
//   PSDate: string | null;
// }

export interface LotDetails {
  SeqNo: number;
  InvoiceLotDetailID: number;
  ItemMasterID: number;
  ItemID: number;
  Barcode: string;
  Description: string;
  Rate: number;
  TaxCode: number;
  TaxAmount: number;
  StdRate: number;
  MRP: number;
  Quantity: number;
  FOCQty: number;
  OrderQty: number;
  Discount: number;
  Amount: number;
  GRPCODE: number;
  InputPer: number;
  EffRate: number;
  Charges: number;
  Icode: string;
  Oemcode: string;
  WSP: number;
  ListedMRP: number;
  OnlineMRP: number;
  SplDiscount: number;
  PSDetailId: number;
}

export interface ChargesDetails {
  chargename: string;
  sign: string;
  type: string;
  amount: string;
  basic: string;
  net: string;
  colhead: string;
  calon: string;
  r_amount: string;
  termcode: string;
  chargecode: string;
  taxcode: number;
}

export interface ReceiveRatioDetails {
  ID: number;
  From: string;
  To: string;
  Ratio: number;
  Qty: number;
}

export interface PostBodyInvoiceData {
  poid: number;
  ponumber: string;
  potype: string;
  basedon: string;
  podate: string;
  loccode: string;
  VendorCode: string;
  dcno: string;
  dcdate: string;
  ValidFrm: string;
  ValidTill: string;
  Stockpoint: number;
  TransportName: string;
  BuyerName: string;
  AgentName: string;
  Remarks: string;
  BasicAmount: string;
  NetAmount: string;
  Round_Off: number;
  PaymentTerm: string;
  OrderMode: string;
  ReqLocationCode: string;
  EmployeeID: string;
  Agentcommission: number;
  CurrencyID: string;
  AgainstID: number;
  LogisticID: number;
  CreatedByOrModifyBy: string;
  CustomField1: string;
  CustomField2: string;
  CustomField3: string;
  CustomField4: string;
  CustomField5: string;
  CFCombo1: string;
  CFCombo2: string;
  CFRadio1: string;
  CFRadio2: string;
  CFDate1: string;
  CFDate2: string;
  //   InvoiceDetails: InvoiceDetails[];
  LotDetails: LotDetails[];
  ChargesDetails: ChargesDetails[];
  ReceiveRatioDetails: ReceiveRatioDetails[];
}
