export interface CollectionRefund {
  entryId: number | null;
  voucherTypeId: number | null;
  voucherNo: string;
  voucherDate: string | null;
  partnerType: string;
  customer: number | null;
  partnerLocation: number | null;
  modeOfPayment: string | null;
  referenctId: number | null;
  referenceNumber: string | null;
  referenceDate: string | null;
  favorOf: string;
  amount: number | string | null;
  narration: string;
  againstIdList: string;
  againstSignList: string;
  againstAmountList: string;
  againstAdjustedAmountList: string;
  againstDiscountAmountList: string;
  againstTdsAmountList: string;
  againstOthersAmountList: string;
  againstAdjustedAmount: number | null;
  againstDiscountAmount: number | null;
  againstTdsAmount: number | null;
  againstOthersAmount: number | null;
  againstRefAmount: number | null;
  newRefAmount: number | null;
  customField1: string;
  customField2: string;
  customField3: string;
  customField4: string;
  customField5: string;
  cfDate1: string | null;
  cfDate2: string | null;
  cfCombo1: string;
  cfCombo2: string;
  cfRadio1: boolean;
  cfRadio2: boolean;
  MOPDetails: any[];
  isActive: boolean;
}
