export interface Party {
  party_code: string;
  party_name: string;
  party_type: string;
  group_code: string;
  contact: string;
  pincode: string;
  ent_id: number;
  telephone: string;
  mobile: string;
  fax: string;
  email: string;
  remarks: string;
  credit_limit: number;
  credit_days: number;
  discount: number;
  balerate: number;
  kg_rate: number;
  rate_each: number;
  commision: number;
  agent_name: string;
  supplier_rate: number | null;
  agent_rate: number;
  transporter_name: string;
  margin_rule: string;
  jobber_rate: number;
  tax_name: string;
  status: string | null;
  user_code: string | null;
  tin_no: string;
  time_stamp: string;
  cst_no: string;
  party_id: string;
  stockpoint_id: string;
  branch_id: any;
  company_code: string | null;
  log_inward: string;
  log_outward: string;
  is_multiple_location: boolean;
  is_active: boolean;
  ledger_id: number;
  payment_term: string;
  payment_term_default: number;
  is_payment: boolean;
  gate_in: boolean;
  gate_out: boolean;
  courier_in: boolean;
  courier_out: boolean;
  gst_no: string;
  gst_type: string;
  pan_no: string;
  ie_code: string | null;
  primary_group: string;
  currency: any;
  mfg: string;
  site_id: string;
  replenishment: boolean;
  sales_forecast: boolean;
  administrator: string;
  password: string;
  created_by: string;
  modified_date: string;
  tax_date: string;
  modified_by: string;
  price_rule: number;
  bank_id: string;
  rating: string;
  landline2: string;
  landline2_code: string;
  landline1_code: string;
  custom_text1: string;
  custom_text2: string;
  custom_text3: string;
  custom_text4: string;
  custom_text5: string;
  custom_combo1: string;
  custom_combo2: string;
  custom_ratio1: number | null;
  customratio2: boolean;
  custom_date1: string;
  custom_date2: string;
  street1: string;
  street2: number;
  area: number;
  city: number;
  zone: number;
  states: number;
  country: number;
  lead_days: number;
  isd_no: number;
  whatsapp_no: string | null;
  defaultterm_code: string | null;
  latitude: string;
  longitude: string;
  account_manager_emp_id: number;
  products_grp_code: any;
  login_username: string | null;
  login_password: string | null;
  is_login_access: boolean;
  billing_for: string;
}

export interface FieldPropsForPartner {
  label: string;
  field: string;
  value: string;
  id: number;
  isReq?: boolean | undefined;
  isVisible?: boolean | undefined;
  maxLength?: number;
}
