// export const urlList: Record<number, Record<number, String>> = {
//   1: {
//     1: "retail-pos",
//     2: "retail-collectionrefund",
//     3: "retail-customer",
//     4: "retail-promotion",
//     5: "retail-salesincentive",
//     6: "retail-loyaltycard",
//     7: "retail-cashverify",
//     8: "retail-returnverify",
//   },
//   2: {
//     1: "procurement-order",
//     2: "procurement-receive",
//     3: "procurement-return",
//     4: "procurement-invoice",
//     5: "procurement-printbarcode",
//     6: "procurement-businesspartner",
//     7: "procurement-charges",
//     8: "procurement-terms",
//     9: "procurement-marginrule",
//     10: "procurement-grncollections",
//     11: "procurement-debitnote",
//   },
//   3: {
//     1: "inventory-productlist",
//     2: "inventory-creategroup",
//     3: "inventory-managestock",
//     4: "inventory-category",
//     5: "inventory-logistics",
//     6: "inventory-stockaudit",
//     7: "inventory-agingmaster",
//     8: "inventory-pricelist",
//     9: "inventory-pricerange",
//     10: "inventory-request",
//     12: "inventory-qctypeconfiguration",
//     13: "inventory-qctemplatemaster",
//     14: "inventory-qcentry",
//   },
//   4: {
//     1: "sales-quote",
//     2: "sales-salesorder",
//     3: "sales-deliverychallan",
//     4: "sales-salesinvoice",
//     5: "sales-salespartner",
//     7: "sales-salesreturn",
//     8: "sales-creditnote",
//   },
//   5: { 1: "finance-naration" },
//   6: {
//     1: "production-process",
//     2: "production-routing",
//     3: "production-service",
//     4: "production-designandstyles",
//     5: "production-joborder",
//     6: "production-jobreceipt",
//     7: "production-orderhistory",
//     8: "production-alteration",
//   },
//   10: {
//     23: "reports-report",
//     33: "dashboard-designer",
//     34: "dashboard-viewer",
//   },
//   13: {
//     1: "admin-sitecreation",
//     2: "admin-user",
//     3: "admin-accessprivilege",
//     4: "admin-taxmaster",
//     5: "admin-salesman",
//     6: "admin-numberingscheme",
//     7: "admin-discountsetup",
//     8: "admin-season",
//     9: "admin-financialyear",
//     10: "admin-transactionapproval",
//     11: "admin-currencyexchangerate",
//     12: "admin-bin",
//   },
//   14: {
//     1: "notification-apps",
//     2: "notification-smstemplate",
//     3: "notification-pinelabs",
//   },
// };

export const urlList: any = {
  1: {
    1: { openComponent: false, url: "retail-pos", create: "retail-pos" },
    2: {
      openComponent: false,
      url: "retail-collectionrefund",
      create: "retail-collectionrefund/create",
    },
    3: {
      openComponent: false,
      url: "retail-customer",
      create: "retail-customer/create",
    },
    4: {
      openComponent: false,
      url: "retail-promotion",
      create: "retail-promotion/create",
    },
    5: {
      openComponent: false,
      url: "retail-salesincentive",
      create: "retail-salesincentive/create",
    },
    6: {
      openComponent: false,
      url: "retail-loyaltycard",
      create: "retail-loyaltycard/create",
    },
    7: {
      openComponent: false,
      url: "retail-cashverify",
      create: "retail-cashverify",
    },
    8: {
      openComponent: false,
      url: "retail-returnverify",
      create: "retail-returnverify",
    },
  },
  2: {
    1: {
      openComponent: true,
      url: "procurement-order",
      create: "procurement-order",
    },
    2: {
      openComponent: true,
      url: "procurement-receive",
      create: "procurement-receive",
    },
    3: {
      openComponent: true,
      url: "procurement-return",
      create: "procurement-return",
    },
    4: {
      openComponent: true,
      url: "procurement-invoice",
      create: "procurement-invoice",
    },
    5: {
      openComponent: false,
      url: "procurement-printbarcode",
      create: "procurement-printbarcode",
    },
    6: {
      openComponent: true,
      url: "procurement-businesspartner",
      create: "procurement-businesspartner",
    },
    7: {
      openComponent: true,
      url: "procurement-charges",
      create: "procurement-charges",
    },
    8: {
      openComponent: false,
      url: "procurement-terms",
      create: "procurement-terms/create",
    },
    9: {
      openComponent: true,
      url: "procurement-marginrule",
      create: "procurement-marginrule",
    },
    10: {
      openComponent: true,
      url: "procurement-grncollections",
      create: "procurement-grncollections",
    },
    11: {
      openComponent: true,
      url: "procurement-debitnote",
      create: "procurement-debitnote",
    },
    12: {
      openComponent: false,
      url: "procurement-paymentvoucher",
      create: "procurement-paymentvoucher/create",
    },
  },
  3: {
    1: {
      openComponent: true,
      url: "inventory-productlist",
      create: "inventory-productlist",
    },
    2: {
      openComponent: false,
      url: "inventory-creategroup",
      create: "inventory-creategroup",
    },
    3: {
      openComponent: false,
      url: "inventory-managestock",
      create: "inventory-managestock",
    },
    4: {
      openComponent: false,
      url: "inventory-category",
      create: "inventory-category",
    },
    5: {
      openComponent: false,
      url: "inventory-logistics",
      create: "inventory-logistics",
    },
    6: {
      openComponent: false,
      url: "inventory-stockaudit",
      create: "inventory-stockaudit/stock-audit-transaction",
    },
    7: {
      openComponent: true,
      url: "inventory-agingmaster",
      create: "inventory-agingmaster",
    },
    8: {
      openComponent: true,
      url: "inventory-pricelist",
      create: "inventory-pricelist",
    },
    9: {
      openComponent: true,
      url: "inventory-pricerange",
      create: "inventory-pricerange",
    },
    10: {
      openComponent: true,
      url: "inventory-request",
      create: "inventory-request",
    },
    12: {
      openComponent: true,
      url: "inventory-qctypeconfiguration",
      create: "inventory-qctypeconfiguration",
    },
    13: {
      openComponent: true,
      url: "inventory-qctemplatemaster",
      create: "inventory-qctemplatemaster",
    },
    14: {
      openComponent: false,
      url: "inventory-qcentry",
      create: "inventory-qcentry/create",
    },
    17: {
      openComponent: false,
      url: "inventory-skumaster",
      create: "inventory-skumaster",
    },
    18: {
      openComponent: false,
      url: "inventory-assortment",
      create: "inventory-assortment",
    },
  },
  4: {
    1: { openComponent: true, url: "sales-quote", create: "sales-quote" },
    2: {
      openComponent: true,
      url: "sales-salesorder",
      create: "sales-salesorder",
    },
    3: {
      openComponent: true,
      url: "sales-deliverychallan",
      create: "sales-deliverychallan",
    },
    4: {
      openComponent: true,
      url: "sales-salesinvoice",
      create: "sales-salesinvoice",
    },
    5: {
      openComponent: true,
      url: "sales-salespartner",
      create: "sales-salespartner",
    },
    7: {
      openComponent: true,
      url: "sales-salesreturn",
      create: "sales-salesreturn",
    },
    8: {
      openComponent: true,
      url: "sales-creditnote",
      create: "sales-creditnote",
    },
    9: {
      openComponent: false,
      url: "sales-receiptvoucher",
      create: "sales-receiptvoucher/create",
    },
  },
  5: {
    1: {
      openComponent: true,
      url: "finance-narration",
      create: "finance-narration",
    },
    2: {
      openComponent: false,
      url: "finance-generalledger",
      create: "finance-generalledger/create",
    },

    4: {
      openComponent: false,
      url: "finance-accountgroup",
      create: "finance-accountgroup",
    },
    5: {
      openComponent: false,
      url: "finance-vouchertype",
      create: "finance-vouchertype",
    },
    6: {
      openComponent: false,
      url: "finance-bankdetails",
      create: "finance-bankdetails",
    },
    7: {
      openComponent: false,
      url: "finance-journalvoucher",
      create: "finance-journalvoucher/create",
    },
    8: {
      openComponent: false,
      url: "finance-balancesheet",
      create: "finance-balancesheet/create",
    },
    9: {
      openComponent: false,
      url: "finance-profitandloss",
      create: "finance-profitandloss/create",
    },
    10: {
      openComponent: false,
      url: "finance-trialbalance",
      create: "finance-trialbalance/create",
    },
    11: {
      openComponent: false,
      url: "finance-vendoroutstanding",
      create: "finance-vendoroutstanding/create",
    },
    12: {
      openComponent: false,
      url: "finance-customeroutstanding",
      create: "finance-customeroutstanding/create",
    },
    13: {
      openComponent: false,
      url: "finance-cashflow",
      create: "finance-cashflow/create",
    },
  },
  6: {
    1: {
      openComponent: true,
      url: "production-process",
      create: "production-process",
    },
    2: {
      openComponent: true,
      url: "production-routing",
      create: "production-routing",
    },
    3: {
      openComponent: true,
      url: "production-service",
      create: "production-service",
    },
    4: {
      openComponent: true,
      url: "production-designandstyles",
      create: "production-designandstyles",
    },
    5: {
      openComponent: true,
      url: "production-joborder",
      create: "production-joborder",
    },
    6: {
      openComponent: true,
      url: "production-jobreceipt",
      create: "production-jobreceipt",
    },
    7: {
      openComponent: false,
      url: "production-orderhistory",
      create: "production-orderhistory",
    },
    8: {
      openComponent: false,
      url: "production-alteration",
      create: "production-alteration/create",
    },
  },
  7: {
    1: {
      openComponent: true,
      url: "payroll-configuration",
      create: "payroll-configuration",
    },
    2: {
      openComponent: true,
      url: "payroll-empgroup",
      create: "payroll-empgroup",
    },
    3: {
      openComponent: true,
      url: "payroll-employee",
      create: "payroll-employee",
    },
    4: {
      openComponent: true,
      url: "payroll-attendance",
      create: "payroll-attendance",
    },
    5: {
      openComponent: true,
      url: "payroll-loanAdvance",
      create: "payroll-loanAdvance",
    },
    6: {
      openComponent: true,
      url: "payroll-salaryprocess",
      create: "payroll-salaryprocess",
    },
    7: {
      openComponent: true,
      url: "payroll-settings",
      create: "payroll-settings",
    },
  },
  10: {
    23: {
      openComponent: true,
      url: "reports-report",
      create: "reports-report",
    },
    33: {
      openComponent: false,
      url: "dashboard-designer",
      create: "dashboard-designer",
    },
    34: {
      openComponent: false,
      url: "dashboard-viewer",
      create: "dashboard-viewer",
    },
  },
  13: {
    1: {
      openComponent: false,
      url: "admin-sitecreation",
      create: "admin-sitecreation/create",
    },
    2: { openComponent: true, url: "admin-user", create: "admin-user" },
    3: {
      openComponent: true,
      url: "admin-accessprivilege",
      create: "admin-accessprivilege",
    },
    4: {
      openComponent: true,
      url: "admin-taxmaster",
      create: "admin-taxmaster",
    },
    5: { openComponent: true, url: "admin-salesman", create: "admin-salesman" },
    6: {
      openComponent: false,
      url: "admin-numberingscheme",
      create: "admin-numberingscheme",
    },
    7: {
      openComponent: true,
      url: "admin-discountsetup",
      create: "admin-discountsetup",
    },
    8: { openComponent: true, url: "admin-season", create: "admin-season" },
    9: {
      openComponent: true,
      url: "admin-financialyear",
      create: "admin-financialyear",
    },
    10: {
      openComponent: false,
      url: "admin-transactionapproval",
      create: "admin-transactionapproval",
    },
    11: {
      openComponent: true,
      url: "admin-currencyexchangerate",
      create: "admin-currencyexchangerate",
    },
    12: { openComponent: true, url: "admin-bins", create: "admin-bins" },
    13: {
      openComponent: false,
      url: "admin-whitelist",
      create: "admin-whitelist",
    },
    14: {
      openComponent: true,
      url: "admin-extrareport",
      create: "admin-extrareport",
    },
  },
  14: {
    1: {
      openComponent: true,
      url: "notification-apps",
      create: "notification-apps",
    },
    2: {
      openComponent: true,
      url: "apps-supportboard",
      create: "apps-supportboard",
    },
    3: {
      openComponent: true,
      url: "apps-ticketingsystem",
      create: "apps-ticketingsystem",
    },
    4: {
      openComponent: true,
      url: "notification-pinelabs",
      create: "notification-pinelabs",
    },
    //  5: {
    //   openComponent: false,
    //   url: "notification-ordermanagementsystem",
    //   create: "notification-ordermanagementsystem",
    // },
    5: {
      openComponent: false,
      url: "apps-feedbackform",
      create: "apps-feedbackform",
    },
  },
};

export const indexList: Record<string, number[]> = {
  Retail: [1, 0, 0, 0],
  POS: [1, 1, 0, 0],
  "Collection Refund": [1, 2, 0, 0],
  Customer: [1, 3, 0, 0],
  Promotion: [1, 4, 0, 0],
  "Sales Incentive": [1, 5, 0, 0],
  "Loyalty Card": [1, 6, 0, 0],
  Procurement: [2, 0, 0, 0],
  Order: [2, 1, 0, 0],
  Receive: [2, 2, 0, 0],
  Return: [2, 3, 0, 0],
  Invoice: [2, 4, 0, 0],
  "Print Barcode": [2, 5, 0, 0],
  "Business Partner": [2, 6, 0, 0],
  Charges: [2, 7, 0, 0],
  Terms: [2, 8, 0, 0],
  "Margin Rule": [2, 9, 0, 0],
  "Debit Note": [2, 11, 0, 0],
  Inventory: [3, 0, 0, 0],
  Product: [3, 1, 0, 0],
  "Product Group": [3, 2, 0, 0],
  "Manage Stock": [3, 3, 0, 0],
  "Inter-Stock Transfer": [3, 3, 1, 0],
  "Bundle Creation": [3, 3, 2, 0],
  "Miscellaneous Stock": [3, 3, 3, 0],
  "Rate Change": [3, 3, 4, 0],
  Requisition: [3, 10, 0, 0],
  Category: [3, 4, 0, 0],
  Logistics: [3, 5, 0, 0],
  "LR Inwards": [3, 5, 1, 0],
  "LR Outwards": [3, 5, 2, 0],
  "Gate Entry ": [3, 5, 3, 0],
  Courier: [3, 5, 4, 0],
  "Stock Audit": [3, 6, 0, 0],
  "Aging Master": [3, 7, 0, 0],
  "Price List": [3, 8, 0, 0],
  "Price Range": [3, 9, 0, 0],
  Sales: [4, 0, 0, 0],
  Quote: [4, 1, 0, 0],
  "Sales Order": [4, 2, 0, 0],
  "Delivery Challan": [4, 3, 0, 0],
  "Sales Invoice": [4, 4, 0, 0],
  "Sales Partner": [4, 5, 0, 0],
  "Sales Return": [4, 7, 0, 0],
  "Credit Note": [4, 8, 0, 0],
  Finance: [5, 0, 0, 0],
  Narration: [5, 1, 0, 0],
  "Voucher Type": [5, 4, 0, 0],
  "Job Order": [6, 5, 0, 0],
  "Job Receipt": [6, 6, 0, 0],
  "Make To Order": [6, 7, 0, 0],
  Service: [6, 3, 0, 0],
  Reports: [10, 0, 0, 0],
  Report: [10, 1, 0, 0],
  Admin: [13, 0, 0, 0],
  Site: [13, 1, 0, 0],
  General: [13, 1, 1, 0],
  "Stock point & Floor": [13, 1, 2, 0],
  StockPoint: [13, 1, 2, 1],
  Floor: [13, 1, 2, 2],
  Terminal: [13, 1, 4, 0],
  "Global Settings": [13, 1, 5, 0],
  "Mode Of Payment": [13, 1, 6, 0],
  "Card Type": [13, 1, 7, 0],
  "About us": [13, 1, 8, 0],
  User: [13, 2, 0, 0],
  "Access Privilege": [13, 3, 0, 0],
  "Tax Master": [13, 4, 0, 0],
  SalesMan: [13, 5, 0, 0],
  "Numbering Scheme": [13, 6, 0, 0],
  "Discount Setup": [13, 7, 0, 0],
  Season: [13, 8, 0, 0],
  "Financial Year": [13, 9, 0, 0],
  "Cash verify": [1, 7, 0, 0],
  "Return Verify": [1, 8, 0, 0],
  "Transaction Approval": [13, 10, 0, 0],
  "Currency Exchange": [13, 11, 0, 0],
  Bin: [13, 12, 0, 0],
  Alteration: [6, 8, 0, 0],
  "Product Master": [3, 11, 0, 0],
  Process: [6, 1, 0, 0],
  Routing: [6, 2, 0, 0],
  "Qc Entry": [3, 14, 0, 0],
  "Qc Type Configuration": [3, 12, 0, 0],
  "Qc Template": [3, 13, 0, 0],
  "Design And Styles": [6, 4, 0, 0],
  "Purchase By Matrix-GRN": [10, 20, 1, 0],
  "Purchase By Bill Wise-GRN": [10, 20, 2, 0],
  "Extra Report": [13, 14, 0, 0],
  Ledgers: [5, 2, 0, 0],
  "Payment Voucher": [2, 12, 0, 0],
  "Receipt Voucher": [4, 9, 0, 0],
  "Account Group": [5, 4, 0, 0],
  "Bank Details": [5, 6, 0, 0],
  "Journal Voucher": [5, 7, 0, 0],
  "SKU Master": [3, 17, 0, 0],
  Assortment: [3, 18, 0, 0],
  "Ticketing System": [14, 3, 0, 0],
};

// Super Admin
export const superindexList: Record<string, number[]> = {
  Tenant: [1, 1, 0],
  Exception: [2, 0, 0],
  Users: [4, 1, 0],
  "Access Privilege": [5, 0, 0],
};

// constant.ts
// export const REPORT_INDEX_MAP: Record<string, number[]> = {
//   "Procurement Report":[10,20,0,0],
//   "Purchase By Matrix-GRN": [10, 20, 1, 0],
//   "Purchase By Bill Wise-GRN": [10, 20, 2, 0],
// };

export const REPORT_INDEX_MAP: Record<
  string,
  [number, number, number, number]
> = {
  "Procurement Report": [10, 20, 0, 0],
  "Purchase By Matrix-GRN": [10, 20, 1, 0],
  "Purchase By Bill Wise-GRN": [10, 20, 2, 0],
  "Purchase By Product-GRN": [10, 20, 3, 0],
  "Purchase By Supplier -GRN": [10, 20, 5, 0],
  "Purchase By Tax -GRN": [10, 20, 6, 0],
  "Pending Logistic": [10, 20, 7, 0],
  "Purchase Order Detail": [10, 20, 8, 0],
  "Logistic Detail": [10, 20, 10, 0],
  "Purchase Summary": [10, 20, 11, 0],
  "Purchase Order Summary": [10, 20, 12, 0],
  "Courier Details": [10, 20, 13, 0],
  "Supplier Outstanding - GRN": [10, 20, 14, 0],
  "Debit Note Summary": [10, 20, 15, 0],
  "Debit Note Detail": [10, 20, 16, 0],
  "Purchase Invoice Summary": [10, 20, 17, 0],
  "Purchase Invoice Detail": [10, 20, 18, 0],
  "Supplier Statement - GRN": [10, 20, 19, 0],
  "Purchase Invoice Cancelled": [10, 20, 21, 0],
  "Debit Note Cancelled": [10, 20, 22, 0],
  "Debit Note Invoice Count": [10, 20, 23, 0],
  "Goods Received Note Cancelled": [10, 20, 24, 0],
  "Goods Return Note Cancelled": [10, 20, 25, 0],

  "Sales - Retail": [10, 21, 0, 0],
  "Cashier Summary": [10, 21, 1, 0],
  "Handover Summary": [10, 21, 2, 0],
  "Cancelled Cash Memo Summary": [10, 21, 3, 0],
  "Bill Entry Type Summary": [10, 21, 4, 0],
  "Cancelled Delivery Slip": [10, 21, 5, 0],
  "Delivery Slip Analysis": [10, 21, 6, 0],
  "Pending Delivery Slips": [10, 21, 7, 0],
  "Sales By Bills": [10, 21, 8, 0],
  "Sales By Product": [10, 21, 9, 0],
  "Sales By Salesman": [10, 21, 10, 0],
  "Sales By Terminal": [10, 21, 11, 0],
  "Sales By Hour": [10, 21, 12, 0],
  "Top Moving Items": [10, 21, 13, 0],
  "Sales By Monthly": [10, 21, 14, 0],
  "Sales By Yearly": [10, 21, 15, 0],
  "Sales By Supplier": [10, 21, 16, 0],
  "Tax Summary": [10, 21, 17, 0],
  "Sales By Matrix": [10, 21, 18, 0],
  "Customer Collections": [10, 21, 19, 0],
  "Customer Outstanding": [10, 21, 20, 0],
  "Customer Statement": [10, 21, 21, 0],
  "Cancelled Cash Memo Detail": [10, 21, 22, 0],
  "Customer Order Taken Detail": [10, 21, 23, 0],
  "Customer Order Taken Summary": [10, 21, 24, 0],
  "Customer Pending Orders": [10, 21, 25, 0],
  "Retail Invoice Count": [10, 21, 26, 0],
  "Fast Moving Item Detail": [10, 21, 27, 0],
  "Sales - Bill Wise SalesOrder Analysis": [10, 21, 28, 0],
  "POS - DeliverySlip Cancel Analysis": [10, 21, 29, 0],
  "POS - Customer Outstanding Report": [10, 21, 30, 0],
  "SalesMan Incentive": [10, 21, 31, 0],
  "Sales - DeliveryChallan Cancel Report": [10, 21, 32, 0],
  "Sales - Customer Statement": [10, 21, 33, 0],
  "POS - Return Verify Report": [10, 21, 35, 0],
  "HandOver Detail": [10, 21, 36, 0],

  "Sales - Wholesale": [10, 22, 0, 0],
  "Sales Quote Summary": [10, 22, 1, 0],
  "Sales Quote Detail": [10, 22, 2, 0],
  "Sales Quote Cancelled": [10, 22, 3, 0],
  "Sales Order Summary": [10, 22, 4, 0],
  "Sales Order Detail": [10, 22, 5, 0],
  "Sales Order Cancelled": [10, 22, 6, 0],
  "Delivery Challan Summary": [10, 22, 7, 0],
  "Sales By Product - DC": [10, 22, 8, 0],
  "Sales By City - DC": [10, 22, 9, 0],
  "Sales By Bill No - DC": [10, 22, 10, 0],
  "Delivery Challan Cancelled": [10, 22, 11, 0],
  "Customer Outstanding - DC": [10, 22, 12, 0],
  "Sales Return Summary": [10, 22, 13, 0],
  ProductExtinct: [10, 22, 14, 0],
  "Sales Invoice Summary": [10, 22, 16, 0],
  "Sales Invoice Detail": [10, 22, 17, 0],
  "Sales Invoice Cancelled": [10, 22, 18, 0],
  "Sales Invoice Bill Count": [10, 22, 19, 0],
  "Credit Note Summary": [10, 22, 20, 0],
  "Credit Note Detail": [10, 22, 21, 0],
  "Credit Note Cancelled": [10, 22, 22, 0],

  "Inventory Report": [10, 23, 0, 0],
  "Miscellaneous Detail": [10, 23, 1, 0],
  "Split Item Detail": [10, 23, 2, 0],
  "Stock Auidt Summary": [10, 23, 3, 0],
  "Closing Stock By Product": [10, 23, 4, 0],
  "Closing Stock By Matrix": [10, 23, 5, 0],
  "Replenishment Plan Detail": [10, 23, 6, 0],
  "Inter Stock Transfer Out Detail": [10, 23, 7, 0],
  "Stock Movement Detail By Product": [10, 23, 8, 0],
  "Closing Stock By Aging": [10, 23, 9, 0],
  "Stock Movement Summary By Supplier": [10, 23, 10, 0],
  "Rate Change Detail": [10, 23, 11, 0],
  "Supplier Transaction History": [10, 23, 12, 0],
  "Stock Movement Detail By Matrix": [10, 23, 13, 0],
  "Inventory - Open To Buy": [10, 23, 14, 0],
  "Bundle List Summary": [10, 23, 15, 0],
  "Stock Verification Summary": [10, 23, 16, 0],
  "Stock Movement Detail With Net Sales": [10, 23, 17, 0],
  "Closing Stock By Supplier": [10, 23, 18, 0],
  "Stock Movement Detail By Supplier": [10, 23, 19, 0],
  "Sales VS Stock Detail": [10, 23, 20, 0],
  "Stock Entry Detail": [10, 23, 21, 0],
  "InterStock Received Report": [10, 23, 22, 0],
  "Stock Movement Summary By Product": [10, 23, 23, 0],
  "Stock Turnover Ratio": [10, 23, 24, 0],
  "Inventory ABC Analysis ": [10, 23, 25, 0],

  // --- Distribution Reports ---
  "Distribution Report": [10, 24, 0, 0],
  "Department Wise Sales Transfer": [10, 24, 1, 0],
  "Matrix Wise Sales Transfer": [10, 24, 2, 0],
  "Department Wise Purchase Transfer": [10, 24, 3, 0],
  "Matrix Wise Purchase Transfer": [10, 24, 4, 0],

  // --- CRM Reports ---
  "CRM Report": [10, 25, 0, 0],
  "Customer RFM Analysis": [10, 25, 1, 0],
  "Customer Revenue Report": [10, 25, 2, 0],
  "Customer Rewards Report": [10, 25, 3, 0],
  "Customer Info Analysis": [10, 25, 4, 0],
  "Points To Voucher": [10, 25, 5, 0],
  "Pos - Customer Statement": [10, 25, 6, 0],
  "Pending GiftVoucher": [10, 25, 7, 0],
  "Points and Voucher Summary": [10, 25, 8, 0],
  "InActive Customer Summary": [10, 25, 9, 0],

  // --- Production Reports ---
  "Production Report": [10, 26, 0, 0],
  "Production Report (Alt)": [10, 26, 1, 0], // appears duplicate in your JSON
  "Production Detail Report": [10, 26, 2, 0],
  "Jobber Production Report": [10, 26, 3, 0],
  "Production Process Report": [10, 26, 4, 0],
  "Jobber OutStanding Report": [10, 26, 5, 0],
  "Jobber Received Report": [10, 26, 6, 0],
  "Service Order Report": [10, 26, 7, 0],

  // --- Store Management / Forecasting ---
  "Store Management Report": [10, 27, 0, 0],
  "Salesman Incentive Report": [10, 27, 1, 0],
  "Sales Promotion Report": [10, 27, 2, 0],
  "Site Forecating Report": [10, 27, 3, 0],
  "Product Forecating Report": [10, 27, 4, 0],
  "Employee Forecasting Report": [10, 27, 5, 0],
  "Gift Item Report": [10, 27, 6, 0],
  "Feedback Report": [10, 27, 7, 0],

  // --- Finance Reports ---
  "Finance Report": [10, 28, 0, 0],
  "Outstanding Report": [10, 28, 1, 0],
  "Flash Report": [10, 28, 2, 0],
  "Account Transaction Report": [10, 28, 3, 0],
  "Day Book Register Report": [10, 28, 4, 0],
  "Agent Wise Payment Tracking Report": [10, 28, 5, 0],
  "Consolidate Balance Sheet": [10, 28, 6, 0],
  "Consolidate Profit & Loss": [10, 28, 7, 0],
  "Consolidate Trial Balance": [10, 28, 8, 0],

  // --- HRMS / Time ---
  "Time And Attendence": [10, 32, 0, 0],
  "Date Wise Log Report": [10, 32, 1, 0],

  // --- Dashboard ---
  "Dashboard Designer": [10, 33, 0, 0],
  "Dashboard Viewer": [10, 34, 0, 0],

  // --- Feedback Form ---
  "Feedback Form": [14, 5, 0, 0],
};
